[build]
  publish = "."
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/proxy"
  function = "proxy"

[[edge_functions]]
  path = "/proxy/*"
  function = "proxy"

[[redirects]]
  from   = "/fetch-playlist"
  to     = "/.netlify/functions/fetch-playlist"
  status = 200
  force  = true

[[redirects]]
  from   = "/license-proxy"
  to     = "/.netlify/functions/license-proxy"
  status = 200
  force  = true

[[redirects]]
  from   = "/stalker-resolve"
  to     = "/.netlify/functions/stalker-resolve"
  status = 200
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
